backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Title", name: "banner_title", widget: "string"}
          - {label: "Banner Subtitle", name: "banner_subtitle", widget: "string"}
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: false}

      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Title", name: "banner_title", widget: "string"}
          - {label: "Banner Subtitle", name: "banner_subtitle", widget: "string"}
          - {label: "Tab 1 Title", name: "tab1_title", widget: "string"}
          - {label: "Tab 1 Content", name: "tab1_content", widget: "markdown"}
          - {label: "Tab 2 Title", name: "tab2_title", widget: "string"}
          - {label: "Tab 2 Content", name: "tab2_content", widget: "markdown"}
          - {label: "Tab 3 Title", name: "tab3_title", widget: "string"}
          - label: "Tab 3 Images"
            name: "tab3_images"
            widget: "list"
            fields:
              - {label: "Image", name: "src", widget: "image", required: false}
              - {label: "Caption", name: "caption", widget: "string"}

      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Mobile Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Website", name: "website", widget: "string"}

      - label: "Footer"
        name: "footer"
        file: "content/footer.md"
        fields:
          - {label: "About Text", name: "about_text", widget: "markdown"}
          - {label: "Mobile Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Copyright", name: "copyright", widget: "string"}

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "baseball-hat"
    label: "Baseball Hat"
    folder: "content/products/baseball-hat"
    create: true
    slug: "product-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", required: false}
      - label: "Product Gallery (Multi Images - Upload all then Publish)"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        label_singular: "Image"
        summary: "{{src}}"
        default:
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
        fields:
          - {label: "Image", name: "src", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "bucket-hat"
    label: "Bucket Hat"
    folder: "content/products/bucket-hat"
    create: true
    slug: "product-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", required: false}
      - label: "Product Gallery (Multi Images - Upload all then Publish)"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        label_singular: "Image"
        summary: "{{src}}"
        default:
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
        fields:
          - {label: "Image", name: "src", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "trucker-hat"
    label: "Trucker Hat"
    folder: "content/products/trucker-hat"
    create: true
    slug: "product-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", required: false}
      - label: "Product Gallery (Multi Images - Upload all then Publish)"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        label_singular: "Image"
        summary: "{{src}}"
        default:
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
        fields:
          - {label: "Image", name: "src", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "dad-hat"
    label: "Dad Hat"
    folder: "content/products/dad-hat"
    create: true
    slug: "product-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", required: false}
      - label: "Product Gallery (Multi Images - Upload all then Publish)"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        label_singular: "Image"
        summary: "{{src}}"
        default:
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
        fields:
          - {label: "Image", name: "src", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "visor-hat"
    label: "Visor Hat"
    folder: "content/products/visor-hat"
    create: true
    slug: "product-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", required: false}
      - label: "Product Gallery (Multi Images - Upload all then Publish)"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        label_singular: "Image"
        summary: "{{src}}"
        default:
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
        fields:
          - {label: "Image", name: "src", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "snapback-hat"
    label: "Snapback Hat"
    folder: "content/products/snapback-hat"
    create: true
    slug: "product-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", required: false}
      - label: "Product Gallery (Multi Images - Upload all then Publish)"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        label_singular: "Image"
        summary: "{{src}}"
        default:
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
        fields:
          - {label: "Image", name: "src", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "beanie"
    label: "Beanie"
    folder: "content/products/beanie"
    create: true
    slug: "product-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main Image", name: "image", widget: "image", required: false}
      - label: "Product Gallery (Multi Images - Upload all then Publish)"
        name: "gallery"
        widget: "list"
        required: false
        collapsed: false
        minimize_collapsed: false
        label_singular: "Image"
        summary: "{{src}}"
        default:
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
          - {src: "", caption: ""}
        fields:
          - {label: "Image", name: "src", widget: "image", required: false}
          - {label: "Caption", name: "caption", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
